
    
spring:
    application:
        name: studeny-service
 
    cloud:
        config:
            uri:
            - http//localhost:8086
           
 
        
                
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            
 
             